version: "1" # version of compose format

services:
  # Node.js Service
  api:
    env_file:
      - .env.dev
    build:
      context: ./server
      target: "${NODE_ENV}" # Target the development stage in the Dockerfile"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    volumes:
      - ./server:/app # Mounts the current directory to the /app directory in the container
      - /app/node_modules # Ensures the container’s node_modules doesn’t conflict with the host’s node_modules
    command: npm run dev

  # MySQL Service
  db:
    env_file:
      - .env.dev
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
